Repository nickkro25/cse112_team15, pull requests merged in 2022-05, with the labels that each got.

#38 top of button now clickable
  index.html
Labels: bug

#4 change readme with current repo info
  README.md
Labels: documentation

#52 Bugfix/save settings
  css/animations.css
  index.html
  js/Misc/Settings.js
  js/Misc/Sounds.js
Labels: bug

#41 Feature/custom-timer-length
  .vscode/settings.json
  css/settings.css
  index.html
  js/Misc/Settings.js
  js/Timer/Timer.js
  js/ToDoList/TodoListDom.js
  tests/distraction.test.js
  tests/statistics.test.js
  tests/timer.test.js
Labels: enhancement

#57 Bug: timer width
  css/style.css
Labels: bug

#60 Bug: Timer Corner, Stats window, Faq box
  css/faq-box.css
  css/stats.css
  css/style.css
Labels: bug

#107 Fixed inconsistent transition speeds from normal to dark mode vice versa.
  css/ThirdParty/reduced-materialize.css
  css/settings.css
  css/table.css
  js/Misc/Settings.js
Labels: bug

#114 Added ask user permission and notifications.
  index.html
  js/Timer/Timer.js
  tests/timer.test.js
Labels: enhancement

#110 updated name of package.json to current repo name
  package.json
Labels: documentation
